[honeypd]
mysql.enabled = True
mysql.port = 3306

ssh.enabled = True
ssh.port = 22

ftp.enabled = True
ftp.port = 21

http.banner = "WebServer/1.0"
http.enabled = True
http.port = 80

https.enabled = True
https.port = 443

smb.enabled = True
smb.port = 445

telnet.enabled = False
telnet.port = 23

syslog_disabled = False
syslog_address = 192.168.50.20
syslog_port = 514
syslog_facility = 16

console.enabled = False

# Logging
logfile.enabled = True
logfile.filepath = /var/log/opencanary/opencanary.log

pyxie.enabled = False

[upnp]
upnp.enabled = False
upnp.port = 1900

[iptables]
iptables.enabled = True
iptables.out_std_whitelist = []
iptables.out_voip_whitelist = []
iptables.in_std_whitelist = []

[snmp]
snmp.enabled = True
snmp.port = 161

[ntp]
ntp.enabled = True
ntp.port = 123

[tftp]
tftp.enabled = False
tftp.port = 69

[vnc]
vnc.enabled = True
vnc.port = 5900

[rdp]
rdp.enabled = True
rdp.port = 3389

[mssql]
mssql.enabled = True
mssql.port = 1433

[postgres]
postgres.enabled = True
postgres.port = 5432

[mongodb]
mongodb.enabled = True
mongodb.port = 27017

[redis]
redis.enabled = True
redis.port = 6379

[cassandra]
cassandra.enabled = True
cassandra.port = 9042

[memcache]
memcache.enabled = True
memcache.port = 11211

[modbus]
modbus.enabled = False
modbus.port = 502

[git]
git.enabled = False
git.port = 9418

