---
# ============================================================================
# SIEM Agent Role - Defaults
# ============================================================================

siem_server: "192.168.50.20"
siem_port: 514
filebeat_version: 8.9.1
auditbeat_version: 8.9.1
osquery_version: latest
